<a href="https://colab.research.google.com/github/SamShinwari/Advanced-AI-Bootcamp-2026/blob/main/Project_1_Text_Cleaning_BBC_Articles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
import string,re
from google.colab import drive
from nltk.corpus import stopwords

#Basic Data Cleaning Project of BBC news articles

In [23]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
file_path = '/content/drive/MyDrive/Colab Notebooks/bbc_dataset.csv'
df = pd.read_csv(file_path)
df.head()

,title,pubDate,guid,link,description
0,Ukraine: Angry Zelensky vows to punish Russian...,"Mon, 07 Mar 2022 08:01:56 GMT",https://www.bbc.co.uk/news/world-europe-60638042,https://www.bbc.co.uk/news/world-europe-606380...,The Ukrainian president says the country will ...
1,War in Ukraine: Taking cover in a town under a...,"Sun, 06 Mar 2022 22:49:58 GMT",https://www.bbc.co.uk/news/world-europe-60641873,https://www.bbc.co.uk/news/world-europe-606418...,"Jeremy Bowen was on the frontline in Irpin, as..."
2,Ukraine war 'catastrophic for global food',"Mon, 07 Mar 2022 00:14:42 GMT",https://www.bbc.co.uk/news/business-60623941,https://www.bbc.co.uk/news/business-60623941?a...,One of the world's biggest fertiliser firms sa...
3,Manchester Arena bombing: Saffie Roussos's par...,"Mon, 07 Mar 2022 00:05:40 GMT",https://www.bbc.co.uk/news/uk-60579079,https://www.bbc.co.uk/news/uk-60579079?at_medi...,The parents of the Manchester Arena bombing's ...
4,Ukraine conflict: Oil price soars to highest l...,"Mon, 07 Mar 2022 08:15:53 GMT",https://www.bbc.co.uk/news/business-60642786,https://www.bbc.co.uk/news/business-60642786?a...,Consumers are feeling the impact of higher ene...

In [25]:
df = df.dropna(subset=["title"])
df = df.drop_duplicates(subset=["title"])
df = df.reset_index(drop=True)

In [26]:
df = df.drop(columns=['guid', 'link','pubDate'])
df.head()

,title,description
0,Ukraine: Angry Zelensky vows to punish Russian...,The Ukrainian president says the country will ...
1,War in Ukraine: Taking cover in a town under a...,"Jeremy Bowen was on the frontline in Irpin, as..."
2,Ukraine war 'catastrophic for global food',One of the world's biggest fertiliser firms sa...
3,Manchester Arena bombing: Saffie Roussos's par...,The parents of the Manchester Arena bombing's ...
4,Ukraine conflict: Oil price soars to highest l...,Consumers are feeling the impact of higher ene...

In [27]:
# Download NLTK resources (run only once)
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

###combine both title and description text

In [28]:
df["text"] = df["title"] + " " + df["description"]

df[["text"]].head()

                                                text
0  Ukraine: Angry Zelensky vows to punish Russian...
1  War in Ukraine: Taking cover in a town under a...
2  Ukraine war 'catastrophic for global food' One...
3  Manchester Arena bombing: Saffie Roussos's par...
4  Ukraine conflict: Oil price soars to highest l...

##preprocessing

In [29]:
df["text"] = df["text"].str.lower()

df["text"].head()

0    ukraine: angry zelensky vows to punish russian...
1    war in ukraine: taking cover in a town under a...
2    ukraine war 'catastrophic for global food' one...
3    manchester arena bombing: saffie roussos's par...
4    ukraine conflict: oil price soars to highest l...
Name: text, dtype: object

##emove punctution

In [30]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df["text"] = df["text"].apply(remove_punctuation)

df["text"].head()

0    ukraine angry zelensky vows to punish russian ...
1    war in ukraine taking cover in a town under at...
2    ukraine war catastrophic for global food one o...
3    manchester arena bombing saffie roussoss paren...
4    ukraine conflict oil price soars to highest le...
Name: text, dtype: object

##data cleaning

In [31]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text)
    return re.sub(r'\s+', ' ', text).strip()

df["text"] = df["text"].apply(remove_numbers)

df["text"].head()

0    ukraine angry zelensky vows to punish russian ...
1    war in ukraine taking cover in a town under at...
2    ukraine war catastrophic for global food one o...
3    manchester arena bombing saffie roussoss paren...
4    ukraine conflict oil price soars to highest le...
Name: text, dtype: object

##stopwords removel

In [34]:
stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    words = text.split()

    filtered = [word for word in words if word not in stop_words]

    return " ".join(filtered)

df["text"] = df["text"].apply(remove_stopwords)

df["text"].head()

0    ukraine angry zelensky vows punish russian atr...
1    war ukraine taking cover town attack jeremy bo...
2    ukraine war catastrophic global food one world...
3    manchester arena bombing saffie roussoss paren...
4    ukraine conflict oil price soars highest level...
Name: text, dtype: object

##use lemmatization

In [37]:
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

df["text"] = df["text"].apply(lemmatize_text)

df["text"].head()

0    ukraine angry zelensky vow punish russian atro...
1    war ukraine taking cover town attack jeremy bo...
2    ukraine war catastrophic global food one world...
3    manchester arena bombing saffie roussoss paren...
4    ukraine conflict oil price soar highest level ...
Name: text, dtype: object

##view final dataset

In [38]:
df[["title", "description", "text"]].head()

,title,description,text
0,Ukraine: Angry Zelensky vows to punish Russian...,The Ukrainian president says the country will ...,ukraine angry zelensky vow punish russian atro...
1,War in Ukraine: Taking cover in a town under a...,"Jeremy Bowen was on the frontline in Irpin, as...",war ukraine taking cover town attack jeremy bo...
2,Ukraine war 'catastrophic for global food',One of the world's biggest fertiliser firms sa...,ukraine war catastrophic global food one world...
3,Manchester Arena bombing: Saffie Roussos's par...,The parents of the Manchester Arena bombing's ...,manchester arena bombing saffie roussoss paren...
4,Ukraine conflict: Oil price soars to highest l...,Consumers are feeling the impact of higher ene...,ukraine conflict oil price soar highest level ...